export const GET_GROUP_THEATER_API = 'GET_GROUP_THEATER_API';
export const GET_GROUP_THEATER_API_SUCCESS = 'GET_GROUP_THEATER_API_SUCCESS'

export const GET_THEATERS_BY_GROUP_API_SUCCESS = 'GET_THEATERS_BY_GROUP_API_SUCCESS';
export const GET_THEATERS_BY_GROUP_API = 'GET_THEATERS_BY_GROUP_API';

export const GET_MOVIE_BY_GROUP_THEATER_API = 'GET_MOVIE_BY_GROUP_THEATER_API';
export const GET_MOVIE_BY_GROUP_THEATER_API_SUCCESS = 'GET_MOVIE_BY_GROUP_THEATER_API_SUCCESS';
