export const SEARCH_MOVIE_GET_MOVIE_LIST = 'SEARCH_MOVIE_GET_MOVIE_LIST';
export const SEARCH_MOVIE_GET_MOVIE_THEATER_LIST = 'SEARCH_MOVIE_GET_THEATER_LIST';
export const SEARCH_MOVIE_DAY = 'SEARCH_MOVIE_DAY';
export const SEARCH_MOVIE_HOUR = 'SEARCH_MOVIE_HOUR';


export const SEARCH_MOVIE_GET_MOVIE_LIST_SUCCESS = 'SEARCH_MOVIE_GET_MOVIE_LIST_SUCCESS';
export const SEARCH_MOVIE_GET_MOVIE_THEATER_LIST_SUCCESS = 'SEARCH_MOVIE_GET_MOVIE_THEATER_LIST_SUCCESS';
export const SEARCH_MOVIE_DAY_SUCCESS = 'SEARCH_MOVIE_DAY_SUCCESS';
export const SEARCH_MOVIE_HOUR_SUCCESS= 'SEARCH_MOVIE_HOUR_SUCCESS';

export const SEARCH_MOVIE_SET_MOVIE_SELECTED = 'SEARCH_MOVIE_SET_MOVIE_SELECTED';
export const SEARCH_MOVIE_SET_THEATER_SELECTED = 'SEARCH_MOVIE_SET_THEATER_SELECTED';
export const SEARCH_MOVIE_SET_DAY_SELECTED = 'SEARCH_MOVIE_SET_DAY_SELECTED';
export const SEARCH_MOVIE_SET_HOUR_SELECTED = 'SEARCH_MOVIE_SET_HOUR_SELECTED';

export const GET_MOVIE_INFO_SCHEDULE_API =  'GET_MOVIE_INFO_SCHEDULE_API';
export const GET_MOVIE_INFO_SCHEDULE_API_SUCCESS = 'GET_MOVIE_INFO_SCHEDULE_API_SUCCESS';